import { HockeySpectator } from 'HockeySpectator';
import { BoxScorePlayer } from './BoxScorePlayer';
import { DevelopmentPhase } from './DevelopmentPhase';
import { HockeyCheck } from './HockeyCheck';
import { HockeyFaceoff } from './HockeyFaceoff';
import { HockeyFight } from './HockeyFight';
import { HockeyGoal } from './HockeyGoal';
import { HockeyLeague } from './HockeyLeague';
import { HockeyPenalty } from './HockeyPenalty';
import { HockeyPeriod } from './HockeyPeriod';
import { HockeyPeriodSummary } from './HockeyPeriodSummary';
import { HockeyPossessionTime } from './HockeyPossessionTime';
import { HockeySeason } from './HockeySeason';
import { HockeySeasonType } from './HockeySeasonType';
import { HockeySeries } from './HockeySeries';
import { HockeyShift } from './HockeyShift';
import { HockeyShot } from './HockeyShot';
import { HockeyStoppage } from './HockeyStoppage';
import { HockeyTeam } from './HockeyTeam';
import { HockeyTournament } from './HockeyTournament';
import { HockeyTurnover } from './HockeyTurnover';
import { HockeyUniform } from './HockeyUniform';
import { IceTimeRecord } from './IceTimeRecord';
import { ShootoutAttempt } from './ShootoutAttempt';

export class BoxScore {
    id?: string;
    date?: Date;
    awayTeam?: HockeyTeam;
    homeTeam?: HockeyTeam;
    winningTeam?: string;
    awayUniform?: HockeyUniform;
    homeUniform?: HockeyUniform;
    awayCount?: number;
    homeCount?: number;
    totalCount?: number;
    duration?: number;
    league?: HockeyLeague;
    season?: HockeySeason;
    seasonType?: HockeySeasonType;
    tournament?: HockeyTournament;
    series?: HockeySeries;
    gameNumber?: number;
    scorer?: string;
    official?: string;
    venue?: string;
    center?: string;
    stream?: string;
    isArcade?: boolean;
    developmentPhase?: DevelopmentPhase;
    isArchived?: boolean;
    players?: BoxScorePlayer[];
    shifts?: HockeyShift[];
    iceTimeRecords?: IceTimeRecord[];
    spectators?: HockeySpectator[];
    periods?: HockeyPeriod[];
    goals?: HockeyGoal[];
    shots?: HockeyShot[];
    faceoffs?: HockeyFaceoff[];
    penalties?: HockeyPenalty[];
    stoppages?: HockeyStoppage[];
    turnovers?: HockeyTurnover[];
    checks?: HockeyCheck[];
    fights?: HockeyFight[];
    shootoutAttempts?: ShootoutAttempt[];
    periodSummaries?: HockeyPeriodSummary[];
    possessionTimes?: HockeyPossessionTime[];
}
