import { HockeyPointsStatistic } from './HockeyPointsStatistic';
import { HockeyStatisticFilter } from './HockeyStatisticFilter';
import { HockeyStreak } from './HockeyStreak';
import { HockeyTurnover } from './HockeyTurnover';
import { HockeyTurnoversStatistic } from './HockeyTurnoversStatistic';
import { Member } from './Member';

export class HockeyPlayerStatistic {
  member?: Member;
  filter?: HockeyStatisticFilter;
  gamesPlayed?: number;
  wins?: number;
  losses?: number;
  draws?: number;
  overtimeWins?: number;
  overtimeLosses?: number;
  shootoutWins?: number;
  shootoutLosses?: number;
  points?: HockeyPointsStatistic[];
  plusMinus?: number;
  penaltyMinutes?: number;
  penaltyMinutesDrawn?: number;
  streak?: HockeyStreak;
  timeOnIce?: number;
  shifts?: number;
  shotsOnGoal?: number;
  missedShots?: number;
  attemptsBlocked?: number;
  blockedShots?: number;
  shotsAgainst?: number;
  saves?: number;
  turnovers?: HockeyTurnoversStatistic[];
  hits?: number;
  hitsTaken?: number;
  faceoffsTaken?: number;
  faceoffsWon?: number;
  faceoffsLost?: number;
  puckPossessionTime?: number;
  puckTouches?: number;
  fights?: number;
  fightsWon?: number;
  fightsLost?: number;
}
